/** Returns the mobile-first, same-origin HTML interface for the throwaway Mini App. */
export function miniAppPage(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Review this week's plan</title>
<style>
:root{color-scheme:light dark;--bg:var(--tg-theme-bg-color,#fff);--text:var(--tg-theme-text-color,#172217);--muted:var(--tg-theme-hint-color,#6f786f);--card:var(--tg-theme-secondary-bg-color,#f3f7f2);--accent:var(--tg-theme-button-color,#2e7d32);--accent-text:var(--tg-theme-button-text-color,#fff);--danger:#bd3030}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.4 system-ui,-apple-system,sans-serif}main{max-width:620px;margin:auto;padding:20px 16px 32px}h1{font-size:24px;line-height:1.15;margin:0 0 4px}p{margin:0}.subtitle{color:var(--muted);margin-bottom:18px}.status{min-height:24px;margin:12px 0;color:var(--muted)}.status.error{color:var(--danger)}.grid{display:grid;gap:10px}.day{background:var(--card);border-radius:14px;padding:12px}.day h2{font-size:16px;margin:0 0 8px}.meal{display:flex;width:100%;gap:10px;align-items:center;text-align:left;background:var(--bg);color:var(--text);border:0;border-radius:10px;padding:11px;margin-top:7px;font:inherit}.meal strong{display:block}.meal small{display:block;color:var(--muted);margin-top:2px}.badge{margin-left:auto;color:#16721c;font-weight:700;font-size:12px}.detail{position:fixed;inset:auto 0 0;background:var(--bg);border-radius:20px 20px 0 0;padding:20px 16px calc(20px + env(safe-area-inset-bottom));box-shadow:0 -4px 24px #0003;transform:translateY(110%);transition:transform .18s ease}.detail.open{transform:translateY(0)}.detail h2{margin:0 0 5px}.detail .description{color:var(--muted);margin-bottom:16px}textarea{display:block;width:100%;min-height:105px;resize:vertical;border:1px solid var(--muted);border-radius:10px;background:var(--bg);color:var(--text);padding:10px;font:inherit}button.primary{width:100%;border:0;border-radius:10px;background:var(--accent);color:var(--accent-text);padding:12px;margin-top:10px;font:inherit;font-weight:700}button.close{background:transparent;border:0;color:var(--muted);font:inherit;float:right;padding:0}.hidden{display:none}.notice{border:1px solid var(--muted);border-radius:12px;padding:14px;margin-top:18px}.footer{color:var(--muted);font-size:13px;margin-top:20px}</style></head>
<body><main><h1>Review this week's plan</h1><p class="subtitle">Tap a meal to collect feedback, then replan when you are ready.</p><div id="status" class="status">Opening your Telegram session…</div><div id="grid" class="grid"></div><button id="replan" class="primary hidden" type="button"></button><div id="handoff" class="notice hidden"><strong>Feedback sent</strong><p>Kipp will continue the review in this Telegram chat.</p></div><div id="browser-notice" class="notice hidden"><strong>Telegram authentication required</strong><p>This page can be inspected in a normal browser, but plan data and feedback only work when opened from Telegram.</p></div><p class="footer">Unsubmitted drafts are saved on this device for this plan and cleared after Replan. Mock server state lasts only while this local Worker keeps running.</p></main>
<section id="detail" class="detail" aria-hidden="true"><button id="close" class="close" type="button">Close</button><h2 id="detail-title"></h2><p id="detail-description" class="description"></p><label for="feedback">What would you change?</label><textarea id="feedback" maxlength="1000" placeholder="e.g. Make this quicker for a busy evening"></textarea><button id="submit" class="primary" type="button">Add feedback</button></section>
<script src="https://telegram.org/js/telegram-web-app.js"></script><script>
const tg=window.Telegram&&window.Telegram.WebApp;let token='',plan=null,target=null,draftKey='';const drafts=new Map();const status=document.querySelector('#status'),grid=document.querySelector('#grid'),detail=document.querySelector('#detail'),feedback=document.querySelector('#feedback'),replan=document.querySelector('#replan'),handoff=document.querySelector('#handoff');
const setStatus=(message,error=false)=>{status.textContent=message;status.className='status'+(error?' error':'')}
const request=(path,options={})=>fetch(path,{...options,headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{}),...(options.headers||{})}})
const readStoredDrafts=()=>new Promise(resolve=>{const done=(value)=>{try{for(const [key,text] of Object.entries(JSON.parse(value||'{}')))if(typeof text==='string')drafts.set(key,text)}catch{}resolve()};if(tg&&tg.DeviceStorage)return tg.DeviceStorage.getItem(draftKey,(_error,value)=>done(value));done(localStorage.getItem(draftKey))})
const writeStoredDrafts=()=>{const value=JSON.stringify(Object.fromEntries(drafts));if(tg&&tg.DeviceStorage)return new Promise(resolve=>tg.DeviceStorage.setItem(draftKey,value,()=>resolve()));localStorage.setItem(draftKey,value);return Promise.resolve()}
const clearStoredDrafts=()=>{if(tg&&tg.DeviceStorage)return new Promise(resolve=>tg.DeviceStorage.removeItem(draftKey,()=>resolve()));localStorage.removeItem(draftKey);return Promise.resolve()}
const render=()=>{grid.innerHTML='';for(const day of plan.days){const section=document.createElement('section');section.className='day';section.innerHTML='<h2>'+day.label+'</h2>';for(const meal of day.meals){const key=day.id+'/'+meal.id;const button=document.createElement('button');button.type='button';button.className='meal';button.innerHTML='<span><strong>'+meal.label+'</strong><small>'+meal.detail+'</small></span>'+(drafts.has(key)?'<span class="badge">Feedback ready</span>':meal.revised?'<span class="badge">Mock revised</span>':'');button.onclick=()=>openDetail(day,meal);section.append(button)}grid.append(section)}replan.textContent='Replan with '+drafts.size+' feedback item'+(drafts.size===1?'':'s');replan.classList.toggle('hidden',drafts.size===0)}
const openDetail=(day,meal)=>{target={day,meal};const key=day.id+'/'+meal.id;document.querySelector('#detail-title').textContent=day.label+' · '+meal.label;document.querySelector('#detail-description').textContent=meal.detail+(meal.feedbackText?' · Applied feedback: '+meal.feedbackText:'');feedback.value=drafts.get(key)||'';detail.classList.add('open');detail.setAttribute('aria-hidden','false');feedback.focus()}
const closeDetail=()=>{detail.classList.remove('open');detail.setAttribute('aria-hidden','true')}
const openSession=async()=>{if(!tg||!tg.initData){document.querySelector('#browser-notice').classList.remove('hidden');setStatus('Open this page from the development bot to test feedback.',true);return}tg.ready();tg.expand();const session=await request('/api/mini-app/session',{method:'POST',body:JSON.stringify({initData:tg.initData})});if(!session.ok)throw new Error((await session.json()).error||'Could not authenticate');const data=await session.json();token=data.sessionToken;const response=await request('/api/mini-app/plan');if(!response.ok)throw new Error('Could not load mock plan');plan=(await response.json()).plan;draftKey='kipp-meal-plan-'+plan.id+'-v'+plan.version;await readStoredDrafts();render();setStatus(drafts.size?'Restored '+drafts.size+' saved feedback item'+(drafts.size===1?'':'s')+'.':'Plan version '+plan.version+' · Select a meal to comment')}
document.querySelector('#close').onclick=closeDetail;document.querySelector('#submit').onclick=async()=>{const text=feedback.value.trim();if(!text){setStatus('Please type feedback before adding it.',true);return}drafts.set(target.day.id+'/'+target.meal.id,text);await writeStoredDrafts();render();closeDetail();setStatus('Feedback saved on this device. Replan when ready.')};replan.onclick=async()=>{const items=[...drafts.entries()].map(([key,text])=>{const [dayId,mealId]=key.split('/');return {dayId,mealId,text}});replan.disabled=true;replan.textContent='Sending…';setStatus('Sending '+items.length+' feedback items to Kipp…');try{const response=await request('/api/mini-app/feedback',{method:'POST',body:JSON.stringify({feedback:items,baseVersion:plan.version,idempotencyKey:crypto.randomUUID()})});const data=await response.json();if(response.status===409){plan=data.plan;render();setStatus(data.error,true);return}if(!response.ok)throw new Error(data.error||'Could not send feedback');drafts.clear();await clearStoredDrafts();grid.innerHTML='';replan.classList.add('hidden');handoff.classList.remove('hidden');setStatus('Feedback sent. Returning to Telegram…');setTimeout(()=>tg&&tg.close&&tg.close(),1500)}catch(error){setStatus(error.message||'Could not send feedback',true)}finally{replan.disabled=false}};
openSession().catch(error=>{setStatus(error.message||'Could not open the Mini App',true)});
</script></body></html>`
}
